#!/bin/bash
DATE=$(date +%Y%m%d)
FORTUNE=$(fortune -s|sed 's/"//g')

git pull
sed -i "s/^\ \ DOCKER_CHEF_SOLO_UPDATED=.*$/  DOCKER_CHEF_SOLO_UPDATED=$DATE/" Dockerfile
git commit -am "$FORTUNE -- $DATE"
